#iiwa:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
    
    
  # Forward Position Controllers ---------------------------------------
  manipulator_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - $(arg robot_name)_joint_1
      - $(arg robot_name)_joint_2
      - $(arg robot_name)_joint_3
      - $(arg robot_name)_joint_4
      - $(arg robot_name)_joint_5
      - $(arg robot_name)_joint_6
      - $(arg robot_name)_joint_7

    constraints:
      goal_time: 0.5                   # Override default
      stopped_velocity_tolerance: 0.0

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default

  # Gripper controller
  gripper_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - finger_joint
      # - gripper_finger1_joint

    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.0
        finger_joint: {trajectory: 0.1, goal: 0.1}
        # gripper_finger1_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.0
    state_publish_rate:  25
    action_monitor_rate: 10

  /kmriiwa:
    gazebo_ros_control:
      pid_gains:
        # gripper
        left_outer_knuckle_joint: {p: 20,  d: 0.1, i: 1, i_clamp: 1}
    arm:
      gazebo_ros_control:
        pid_gains:
          # gripper
          finger_joint: {p: 10,  d: 0.1, i: 1, i_clamp: 1}

  ## before the gripper_controller
  # /kmriiwa:
  #   arm:
  #     gazebo_ros_control:
  #       pid_gains:
  #         kmriiwa_joint_1:
  #           p: 100.0
  #           i: 0.01
  #           d: 10.0
  #         kmriiwa_joint_2:
  #           p: 100.0
  #           i: 0.01
  #           d: 10.0
  #         kmriiwa_joint_3:
  #           p: 100.0
  #           i: 0.01
  #           d: 10.0
  #         kmriiwa_joint_4:
  #           p: 100.0
  #           i: 0.01
  #           d: 10.0
  #         kmriiwa_joint_5:
  #           p: 100.0
  #           i: 0.01
  #           d: 10.0
  #         kmriiwa_joint_6:
  #           p: 100.0
  #           i: 0.01
  #           d: 10.0
  #         kmriiwa_joint_7:
  #           p: 100.0
  #           i: 0.01
  #           d: 10.0  
