controller_list:
  - name: fake_$(arg robot_name)_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - $(arg robot_name)_joint_1
      - $(arg robot_name)_joint_2
      - $(arg robot_name)_joint_3
      - $(arg robot_name)_joint_4
      - $(arg robot_name)_joint_5
      - $(arg robot_name)_joint_6
      - $(arg robot_name)_joint_7 

  - name: fake_$(arg robot_name)_hand_controller
    type: $(arg fake_execution_type)
    joints:
      # - gripper_finger1_joint
      - finger_joint

initial:  # Define initial robot poses per group
  - group: $(arg robot_name)_manipulator
    pose: home
  - group: gripper
    pose: open