<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


  <!-- Import Gazebo-settings -->
  <xacro:include filename="$(find kmriiwa_description)/urdf/kmp200/kmp200.gazebo.xacro" />

  <!-- some technical data constants obtained from KMP200 manual-->
  <xacro:property name="base_length" value="1.08" />
  <xacro:property name="base_height" value="0.7" />
  <xacro:property name="base_width" value="0.63" />
  <xacro:property name="base_mass" value="390" />
  <xacro:property name="center_of_gravity_height_noload" value="0.26" />
  <xacro:property name="wheel_radius" value="0.125" />
  <xacro:property name="wheel_thickness" value="0.132" />
  <xacro:property name="track_gauge" value="0.365" />
  <xacro:property name="wheel_base" value="0.56" />

  <xacro:property name="ground_clearance" value="0.025" /> <!-- distance from wheel-floor contact point to base bottom side-->

  <xacro:macro name="kmp200" params="robot_name">

    <link name="${robot_name}_base_footprint"/>

    <joint name="${robot_name}_footprint_to_base_link" type="fixed">
        <parent link="${robot_name}_base_footprint"/>
        <child link="${robot_name}_base_link"/>
        <origin rpy="0 0 0.0" xyz="0 0 ${ground_clearance}"/>
    </joint>


    <link name="${robot_name}_base_link">
    	<origin rpy="0 0 0" xyz="0 0 0"/>
        <visual>
          <geometry>
            <mesh filename="package://kmriiwa_description/meshes/kmp200/KMP200.dae"/>
          </geometry>
          <material name="White"/>
        </visual>
        <collision>
          <geometry>
            <mesh filename="package://kmriiwa_description/meshes/kmp200/KMP200.dae"/>
          </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 ${center_of_gravity_height_noload-ground_clearance}" rpy="0 0 0"/>
            <mass value="${base_mass}"/>
            <!-- obtained from KMP200 model on fusion 360 with some modification to align center of mass with the given one-->
            <inertia ixx="28.95" ixy="0.0" ixz="0.0" iyy="44.03" iyz="0.0" izz="33.83"/>
        </inertial>
    </link>
    
    <joint name="${robot_name}_base_link_to_top" type="fixed">
        <parent link="${robot_name}_base_link"/>
        <child link="${robot_name}_base_top_link"/>
        <origin rpy="0 0 0.0" xyz="0 0 ${base_height-ground_clearance}"/>
    </joint>
    
    <link name="${robot_name}_base_top_link"/>

    <joint name="${robot_name}_laser_B1_joint" type="fixed">
            <parent link="${robot_name}_base_link" />
            <child link="${robot_name}_laser_B1_link" />
            <origin xyz="0.464 -0.256 0.1168" rpy="0 0 -0.7854"/>
    </joint>

    <link name="${robot_name}_laser_B1_link">
        <visual>
          <origin xyz="0 0 0" rpy="3.1413 0 0"/>
          <geometry>
              <mesh filename="package://kmriiwa_description/meshes/kmp200/sensors/visual/sick_lms1xx.dae" />
          </geometry>
          <material name="DarkGrey"/>
        </visual>
        <collision>
            <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://kmriiwa_description/meshes/kmp200/sensors/collision/sick_lms1xx.stl" />
            </geometry>
        </collision>
        <inertial>
            <mass value="1.2"/>
            <inertia ixx="0.002355" ixy="0.0" ixz="0.0" iyy="0.002355" iyz="0.0" izz="0.0002809"/>
        </inertial>
    </link>

    <joint name="${robot_name}_laser_B4_joint" type="fixed">
            <parent link="${robot_name}_base_link" />
            <child link="${robot_name}_laser_B4_link" />
            <origin xyz="-0.464 0.256 0.1168" rpy="0 0 2.3562"/>
    </joint>

    <link name="${robot_name}_laser_B4_link">
        <visual>
          <origin xyz="0.0 0 0" rpy="0 3.1413 3.1413"/>
          <geometry>
              <mesh filename="package://kmriiwa_description/meshes/kmp200/sensors/visual/sick_lms1xx.dae" />
          </geometry>
          <material name="DarkGrey"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                  <mesh filename="package://kmriiwa_description/meshes/kmp200/sensors/collision/sick_lms1xx.stl" />
            </geometry>
        </collision>
        <inertial>
            <mass value="1.2"/>
            <inertia ixx="0.002355" ixy="0.0" ixz="0.0" iyy="0.002355" iyz="0.0" izz="0.0002809"/>
        </inertial>
    </link>

    <link name="${robot_name}_front_left_wheel_link">
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://kmriiwa_description/meshes/kmp200/wheels/omni_wheel_1.dae" scale="1.06695 1.06695 1.06695"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="0 0 0" rpy="1.57 0 0" />
          <geometry>
            <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
          </geometry>
        </collision>
    </link>

    <link name="${robot_name}_front_right_wheel_link">
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://kmriiwa_description/meshes/kmp200/wheels/omni_wheel_1.dae" scale="1.06695 1.06695 1.06695"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="0 0 0" rpy="1.57 0 0" />
          <geometry>
            <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
          </geometry>
        </collision>
    </link>

    <link name="${robot_name}_back_left_wheel_link">
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://kmriiwa_description/meshes/kmp200/wheels/omni_wheel_1.dae" scale="1.06695 1.06695 1.06695"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="0 0 0" rpy="1.57 0 0" />
          <geometry>
            <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
          </geometry>
        </collision>
    </link>

    <link name="${robot_name}_back_right_wheel_link">
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://kmriiwa_description/meshes/kmp200/wheels/omni_wheel_1.dae" scale="1.06695 1.06695 1.06695"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="0 0 0" rpy="1.57 0 0" />
          <geometry>
            <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
          </geometry>
        </collision>
        <!-- <inertial>
            <mass value="14"/>
            <inertia ixx="0.075016" ixy="0.0" ixz="0.0" iyy="0.075016" iyz="0.0" izz="0.109375"/>
        </inertial> -->
    </link>

    <joint name="${robot_name}_front_left_wheel_joint" type="fixed">
        <parent link="${robot_name}_base_link"/>
        <child link="${robot_name}_front_left_wheel_link"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${wheel_base/2} ${track_gauge/2} ${wheel_radius-ground_clearance}"/>
        <limit effort="100" velocity="100"/>
        <joint_properties damping="0.0" friction="0.0"/>
    </joint>

    <joint name="${robot_name}_front_right_wheel_joint" type="fixed">
        <parent link="${robot_name}_base_link"/>
        <child link="${robot_name}_front_right_wheel_link"/>
        <origin xyz="${wheel_base/2} ${-1*track_gauge/2} ${wheel_radius-ground_clearance}"/>
        <axis xyz="0 1 0"/>
        <limit effort="100" velocity="100"/>
        <joint_properties damping="0.0" friction="0.0"/>
    </joint>

    <joint name="${robot_name}_back_left_wheel_joint" type="fixed">
        <parent link="${robot_name}_base_link"/>
        <child link="${robot_name}_back_left_wheel_link"/>
        <origin xyz="${-1*wheel_base/2} ${track_gauge/2} ${wheel_radius-ground_clearance}"/>
        <axis xyz="0 1 0"/>
        <limit effort="100" velocity="100"/>
        <joint_properties damping="0.0" friction="0.0"/>
    </joint>

    <joint name="${robot_name}_back_right_wheel_joint" type="fixed">
        <parent link="${robot_name}_base_link"/>
        <child link="${robot_name}_back_right_wheel_link"/>
        <origin xyz="${-1*wheel_base/2} ${-1*track_gauge/2} ${wheel_radius-ground_clearance}"/>
        <axis xyz="0 1 0"/>
        <limit effort="100" velocity="100"/>
        <joint_properties damping="0.0" friction="0.0"/>
    </joint>

    <!--Extensions -->
    <xacro:kmp200_gazebo robot_name="${robot_name}"/>

   </xacro:macro>

</robot>
