footprint: [[0.506, 0.315], [0.506, -0.315], [-0.506, -0.315], [-0.506, 0.315]]
footprint_padding: 0.1

robot_base_frame: $(arg robot_name)_base_link
update_frequency: 5.0
publish_frequency: 5.0
transform_tolerance: 0.5

resolution: 0.1

obstacle_range: 2.0
raytrace_range: 2.5

#layer definitions
static:
  map_topic: map
  subscribe_to_updates: true

obstacles:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: $(arg robot_name)_base_link, data_type: LaserScan, topic: scan_multi, marking: true, clearing: true}

# inflation_layer:
#   inflation_radius: 2
