odom_frame: $(arg robot_name)_odom
base_frame: $(arg robot_name)_base_link
map_frame: map

map_update_interval: 0.5 # Publish new map

maxUrange: 14.5 # Should be just less than sensor range
maxRange: 15.5 # Should be just greater than sensor range
particles: 30 # Increased from 80

# Update frequencies
linearUpdate: 0.1
angularUpdate: 0.1
temporalUpdate: 1.0
resampleThreshold: 0.5

# Initial Map Size
xmin: -10.0
ymin: -10.0
xmax: 10.0
ymax: 10.0
delta: 0.05

# All default
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005