local_costmap:
  global_frame: $(arg robot_name)_odom
  static_map: false
  rolling_window: true
  width: 5
  height: 5

  plugins:
  - {name: obstacles,       type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  inflation_radius: 0.1
  cost_scaling_factor: 1.5